const fs = require('fs')
const { parseKeymapFile } = require('./dts-parser')

function encodeCombo(combo) {
  const lines = []
  lines.push(`        ${combo.name} {`)
  lines.push(`            bindings = <${combo.bindings}>;`)
  lines.push(`            key-positions = <${combo.keyPositions.join(' ')}>;`)

  if (combo.layers && combo.layers.length > 0) {
    lines.push(`            layers = <${combo.layers.join(' ')}>;`)
  }

  if (combo.timeout && combo.timeout !== 30) {
    lines.push(`            timeout-ms = <${combo.timeout}>;`)
  }

  if (combo.requirePriorIdleMs) {
    lines.push(`            require-prior-idle-ms = <${combo.requirePriorIdleMs}>;`)
  }

  if (combo.slowRelease) {
    lines.push(`            slow-release;`)
  }

  lines.push(`        };`)
  return lines.join('\n')
}

function encodeCombos(combos) {
  if (!combos || combos.length === 0) return ''

  const lines = []
  lines.push('    combos {')
  lines.push('        compatible = "zmk,combos";')
  lines.push('')

  for (const combo of combos) {
    lines.push(encodeCombo(combo))
    lines.push('')
  }

  lines.push('    };')
  return lines.join('\n')
}

function encodeLayer(bindings, name, index) {
  const layerName = name
    ? name.replace(/[^a-zA-Z0-9_]/g, '_')
    : (index === 0 ? 'default_layer' : `layer_${index}`)

  const lines = []
  lines.push(`        ${layerName} {`)
  lines.push(`            bindings = <`)

  // Format bindings in rows (assume 10 per row for 34-key split)
  const rowSize = 10
  for (let i = 0; i < bindings.length; i += rowSize) {
    const row = bindings.slice(i, i + rowSize)
    lines.push(`                ${row.join(' ')}`)
  }

  lines.push(`            >;`)
  lines.push(`        };`)
  return lines.join('\n')
}

function encodeLayers(layers, layerNames) {
  const lines = []
  for (let i = 0; i < layers.length; i++) {
    lines.push(encodeLayer(layers[i], layerNames?.[i], i))
    if (i < layers.length - 1) lines.push('')
  }
  return lines.join('\n')
}

function encodeKeymap(keymap, options = {}) {
  const { includeHeader = true, template } = options

  const lines = []

  if (includeHeader) {
    lines.push('/*')
    lines.push(' * ZMK Keymap')
    lines.push(' * Generated by keymap-editor')
    lines.push(' */')
    lines.push('')
    lines.push('#include <behaviors.dtsi>')
    lines.push('#include <dt-bindings/zmk/keys.h>')
    lines.push('#include <dt-bindings/zmk/bt.h>')
    lines.push('')
  }

  lines.push('/ {')

  // Combos section
  if (keymap.combos && keymap.combos.length > 0) {
    lines.push(encodeCombos(keymap.combos))
    lines.push('')
  }

  // Keymap section
  lines.push('    keymap {')
  lines.push('        compatible = "zmk,keymap";')
  lines.push('')
  lines.push(encodeLayers(keymap.layers, keymap.layer_names))
  lines.push('    };')

  lines.push('};')

  return lines.join('\n')
}

function updateCombosInFile(filePath, newCombos) {
  const content = fs.readFileSync(filePath, 'utf-8')

  // Find combos section and replace it
  const combosRegex = /(\s*combos\s*\{[\s\S]*?compatible\s*=\s*"zmk,combos"[\s\S]*?\n\s*\};)/

  if (combosRegex.test(content)) {
    const newCombosSection = encodeCombos(newCombos)
    return content.replace(combosRegex, newCombosSection)
  } else {
    // Insert combos section after "/ {"
    const rootRegex = /(\/\s*\{)/
    const newCombosSection = '\n' + encodeCombos(newCombos) + '\n'
    return content.replace(rootRegex, '$1' + newCombosSection)
  }
}

module.exports = {
  encodeCombo,
  encodeCombos,
  encodeLayer,
  encodeLayers,
  encodeKeymap,
  updateCombosInFile
}
